#!/bin/bash

SOURCEPATH="/var/lib/nextcloud/ckn/files/SofortUpload/AutoSort/"
DESTINATIONPATH="/var/lib/nextcloud/ckn/files/Bilder/Chronologie/"
USER="ckn"

if ps aux | grep cron | grep nc-picsort; then echo "EXIT: still running"; exit 0; fi

SCAN="FALSE"
IFS=$'\n'
for f in `find "$SOURCEPATH" -iname *.JPG -o -iname *.CR2 -o -iname *.MP4 -o -iname *.MOV`; do
  SCAN="TRUE"
  DATE=`exiftool "$f" | grep -m 1 "Create Date"`
  if ! echo "$DATE" | grep "Create Date" >/dev/null; then echo "SKIP: no 'Create Date' in exif ($f)"; continue; fi
  YEAR=`echo $DATE | cut -d':' -f2 | cut -c 2-`
  MONTH=`echo $DATE | cut -d':' -f3`
  DAY=`echo $DATE | cut -d':' -f4 | cut -d' ' -f1`
  HOUR=`echo $DATE | cut -d':' -f4 | cut -d' ' -f2`
  MINUTE=`echo $DATE | cut -d':' -f5`
  SECOND=`echo $DATE | cut -d':' -f6`
  HASH=`sha256sum "$f" | xxd -r -p | base64 | head -c 3 | tr '/+' '_-'`
  EXT=`basename "$f" | cut -d'.' -f2 | tr '[:upper:]' '[:lower:]'`
  if [[ "$EXT" = "cr2" ]]; then RAW="raw/"; else RAW=""; fi
  FILE="$DESTINATIONPATH/$YEAR-$MONTH/$RAW$YEAR$MONTH$DAY"-"$HOUR$MINUTE$SECOND"_"$HASH"."$EXT"
  mkdir -p "$(dirname "$FILE")"
  mv -v "$f" "$FILE"
done

if  [ "$SCAN" == "TRUE" ]; then
  find "$SOURCEPATH" -type d -empty -delete
  chown -R www-data:www-data "$DESTINATIONPATH"
  chmod -R 777 "$DESTINATIONPATH"
  sudo -u www-data php /var/www/nextcloud/occ files:scan $USER
  sudo -u www-data php /var/www/nextcloud/occ preview:generate-all $USER
fi
